### ISSUE TITLE
Support sensitive values merge

### ISSUE THREAD

**Issue by janschumann** [cloudposse/terraform-provider-utils#44]
Since terraform 0.15 sensitive values are treated carefully throughout terraform itself. But resources need to declare inputs as sensitive to benefit from that change. It would be great to be able to merge sensitive values.

I would propose to either
- create a new resource `utils_sensitive_deep_merge_yaml` where `input` and `output` schemas are declared sensible
- or add `sensitive_input` and `sensitive_output` schemas to the existing resource

What do you think? In case you are interested, I would quickly prepare a PR.

**Comment by aknysh** [comment]
@janschumann  thank you, it's interesting, please prepare a PR, we'll review promptly
